// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1p_W4P6xX_Eosrngddi52OP4fMFgWXHY',
    appId: '1:367283492948:web:20fc13bbd289fde89a75c1',
    messagingSenderId: '367283492948',
    projectId: 'zyad-80c03',
    authDomain: 'zyad-80c03.firebaseapp.com',
    storageBucket: 'zyad-80c03.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaHXEAnHFOGBtxqKFPY3Pb5KdvFWCYdU0',
    appId: '1:367283492948:android:3de27c773dc90dc09a75c1',
    messagingSenderId: '367283492948',
    projectId: 'zyad-80c03',
    storageBucket: 'zyad-80c03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaGkb9e3qRyDNl4VOy7hXBuh4Fly-5Qew',
    appId: '1:367283492948:ios:0c111a78df29b7ac9a75c1',
    messagingSenderId: '367283492948',
    projectId: 'zyad-80c03',
    storageBucket: 'zyad-80c03.appspot.com',
    iosClientId: '367283492948-0cm3pel57idfr5o2lfj8194eh8dcjgv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaGkb9e3qRyDNl4VOy7hXBuh4Fly-5Qew',
    appId: '1:367283492948:ios:c4b102be6b518d609a75c1',
    messagingSenderId: '367283492948',
    projectId: 'zyad-80c03',
    storageBucket: 'zyad-80c03.appspot.com',
    iosClientId: '367283492948-q1nqd54qt5rekjjde31u8hjl0vm69b3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocApp.RunnerTests',
  );
}
